#!/bin/bash
NAME=PRJ_NAME                                  # Name of the application
DJANGODIR=PRJ_PATH             # Django project directory
SOCKFILE=PRJ_PATH/PRJ_NAME/run/gunicorn.sock  # use this unix socket
USER=PRJ_NAME                                        # the user to run as
GROUP=PRJ_NAME                                 # the group to run a
NUM_WORKERS=1                                     # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=PRJ_NAME.settings.base             # which settings file should Django use
DJANGO_WSGI_MODULE=PRJ_NAME.wsgi                     # WSGI module name
 
echo "Starting $NAME as `whoami`"
 
# Activate the virtual environment
cd $DJANGODIR
source .env/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH
 
# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR
 
# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec PRJ_PATH/PRJ_NAME/.env/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --bind=unix:$SOCKFILE \
  --log-level=debug \
  --log-file=-
  #--bind=localhost:8001

