"""
Django settings for rss_crawler project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT_ROOT = os.path.join(BASE_DIR, os.path.pardir)
PROJECT_VARIABLES = {
        'PROJECT_NAME': 'django_start',
        'DB_PASSWORD': 'password',
        'DB_RO_PASSWORD': 'read_only',
        'DB_HOST': 'localhost'}

PROJECT_NAME = PROJECT_VARIABLES['PROJECT_NAME']
DB_PASSWORD = PROJECT_VARIABLES['DB_PASSWORD']
DB_HOST = PROJECT_VARIABLES['DB_HOST']

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'secret'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost']


# Application definition

INSTALLED_APPS = (
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
        'djcelery',
        'kombu.transport.django',
        )

MIDDLEWARE_CLASSES = (
        'django.contrib.sessions.middleware.SessionMiddleware',
        'django.middleware.common.CommonMiddleware',
        'django.middleware.csrf.CsrfViewMiddleware',
        'django.contrib.auth.middleware.AuthenticationMiddleware',
        'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
        'django.contrib.messages.middleware.MessageMiddleware',
        'django.middleware.clickjacking.XFrameOptionsMiddleware',
        'django.middleware.security.SecurityMiddleware',
        )

ROOT_URLCONF = '%s.urls' % PROJECT_NAME

TEMPLATES = [
        {
            'BACKEND': 'django.template.backends.django.DjangoTemplates',
            'DIRS': os.path.join(PROJECT_ROOT, 'templates'),
            'APP_DIRS': True,
            'OPTIONS': {
                'context_processors': [
                    'django.template.context_processors.debug',
                    'django.template.context_processors.request',
                    'django.contrib.auth.context_processors.auth',
                    'django.contrib.messages.context_processors.messages',
                    ],
                },
            },
        ]

WSGI_APPLICATION = '%s.wsgi.application' % PROJECT_NAME


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': PROJECT_NAME,
            'USER': PROJECT_NAME,
            'HOST': DB_HOST,
            'PASSWORD': DB_PASSWORD
            }
        }


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = '%s.static' % PROJECT_NAME

LOGGING = {                                                                  
        'version': 1,                                                            
        'disable_existing_loggers': False,                                       
        'formatters': {                                                          
            'default': {                                                         
                'format' : '[%(asctime)s %(levelname)s] (%(name)s) %(message)s', 
                'datefmt' : '%Y-%m-%d %H:%M:%S'                                  
                }                                                                    
            }                                                                        
        }                                                                            

# CELERY SETTINGS
import djcelery
BROKER_URL = "django://"
djcelery.setup_loader()

if __name__ == "__main__":
    print project_root
